#
# Cookbook Name:: poldek
# Provider:: repository
#
# Copyright 2016, Elan Ruusamäe
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

use_inline_resources

def whyrun_supported?
  true
end

def bool_option(option)
  option ? 'yes' : 'no'
end

# build repo file contents
def build_repo(name, path, type, auto, autoup, ignore) # rubocop: disable Metrics/ParameterLists
  ignore = ignore.join(' ') if ignore.respond_to?(:join)
  repo_options = []
  repo_options << "type = #{type}"
  repo_options << "name = #{name}"
  repo_options << "path = #{path}"
  repo_options << "auto = #{bool_option(auto)}"
  repo_options << "autoup = #{bool_option(autoup)}"
  repo_options << "ignore = #{ignore}"  unless ignore.empty?

  repo = "# This file was generated by Chef\n\n"
  repo = "[source]\n"
  repo << repo_options.join("\n")
  repo << "\n"
  repo
end

action :add do
  repo_file = "/etc/poldek/repos.d/#{new_resource.name}.conf"
  # build repo file
  repository = build_repo(
      new_resource.repo_name,
      new_resource.path,
      new_resource.type,
      new_resource.auto,
      new_resource.autoup,
      new_resource.ignore
  )

  file repo_file do
    owner 'root'
    group 'root'
    mode '0644'
    content repository
    action :create
  end
end

action :remove do
  repo_file = "/etc/poldek/repos.d/#{new_resource.name}.conf"
  if ::File.exist?(repo_file)
    Chef::Log.info "Removing #{new_resource.name} repository from /etc/poldek/repos.d"
    file repo_file do
      action :delete
    end
  end
end
